# Generated by Django 4.0.5 on 2022-06-21 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('third_eye_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='third_eye_app.profile')),
            ],
        ),
    ]
