# Generated by Django 4.0.5 on 2022-06-22 01:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('third_eye_app', '0004_business_user_profile_user_user_posts_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Profile_thirdeye',
        ),
    ]
