# Generated by Django 4.0.5 on 2022-06-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_eye_app', '0005_rename_profile_profile_thirdeye'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_thirdeye',
            name='bio',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profile_thirdeye',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile_thirdeye',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile_thirdeye',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
