# Generated by Django 4.0.5 on 2022-06-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_eye_app', '0006_profile_thirdeye_bio_profile_thirdeye_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_thirdeye',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile_thirdeye',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
